package com.wxapp.cms.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_buy_history", "id", BuyHistory.class);
		arp.addMapping("t_custom", "id", Custom.class);
		arp.addMapping("t_label", "id", Label.class);
		arp.addMapping("t_price_history", "id", PriceHistory.class);
		arp.addMapping("t_setting", "id", Setting.class);
		arp.addMapping("t_store", "id", Store.class);
		arp.addMapping("t_user", "id", User.class);
	}
}

