package com.wxapp.cms.model;

import com.wxapp.cms.model.base.BaseBuyHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BuyHistory extends BaseBuyHistory<BuyHistory> {
    /**
     * 未赠送
     */
    public static final String FREE = "0";
    /**
     * 已赠送
     */
    public static final String UNFREE = "1";
}
