package com.wxapp.cms.model;

import com.wxapp.cms.model.base.BasePriceHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PriceHistory extends BasePriceHistory<PriceHistory> {
	
}
