package com.wxapp.cms.model;

import com.wxapp.cms.model.base.BaseSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Setting extends BaseSetting<Setting> {
    /**
     * 开启
     */
    public static final String ENABLED = "0";
    /**
     * 关闭
     */
    public static final String DISABLED = "1";
    /**
     * 默认列表数
     */
    public static final int LIST_SIZE = 10;
}
