package com.wxapp.cms.model;

import com.wxapp.cms.model.base.BaseStore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Store extends BaseStore<Store> {
	public static final int NOW_NUM = 0;
}
