package com.wxapp.cms.model;

import com.wxapp.cms.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
    /**
     * 正常
     */
    public static final String ENABLED = "0";
    /**
     * 冻结
     */
    public static final String DISABLED = "1";
    /**
     * 试用
     */
    public static final String TRYOUT = "2";
    /**
     * 试用天数
     */
    public static final int TRYDAYS = 3;
}
