package com.wxapp.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBuyHistory<M extends BaseBuyHistory<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCustom(java.lang.Integer custom) {
		set("custom", custom);
		return (M)this;
	}
	
	public java.lang.Integer getCustom() {
		return getInt("custom");
	}

	public M setBuyDate(java.util.Date buyDate) {
		set("buy_date", buyDate);
		return (M)this;
	}
	
	public java.util.Date getBuyDate() {
		return get("buy_date");
	}

	public M setFree(java.lang.String free) {
		set("free", free);
		return (M)this;
	}
	
	public java.lang.String getFree() {
		return getStr("free");
	}

}
