package com.wxapp.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSetting<M extends BaseSetting<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setListSize(java.lang.Integer listSize) {
		set("list_size", listSize);
		return (M)this;
	}
	
	public java.lang.Integer getListSize() {
		return getInt("list_size");
	}

	public M setTime(java.lang.String time) {
		set("time", time);
		return (M)this;
	}
	
	public java.lang.String getTime() {
		return getStr("time");
	}

	public M setFree(java.lang.Integer free) {
		set("free", free);
		return (M)this;
	}
	
	public java.lang.Integer getFree() {
		return getInt("free");
	}

	public M setGift(java.lang.String gift) {
		set("gift", gift);
		return (M)this;
	}
	
	public java.lang.String getGift() {
		return getStr("gift");
	}

}
